definitions:
  models.Subject:
    properties:
      id:
        type: integer
      name:
        type: string
      status:
        type: boolean
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /subjects:
    post:
      consumes:
      - application/json
      description: Create a new subject with the input payload
      parameters:
      - description: Create subject
        in: body
        name: subject
        required: true
        schema:
          $ref: '#/definitions/models.Subject'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Subject'
      summary: Create a new subject
      tags:
      - subjects
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user with the input payload
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
